name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Copy artifacts
      run: mkdir -p ./out/ && cp -t ./out/ **/target/eZProtector-*.jar
    - uses: actions/upload-artifact@v3
      with:
        name: Plugin JARs
        path: out/

