name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Upload Paper version
      uses: actions/upload-artifact@v1
      with:
        name: Paper
        path: paper/target/eZProtector-Paper.jar
    - name: Upload Sponge version
      uses: actions/upload-artifact@v1
      with:
        name: Sponge
        path: sponge/target/eZProtector-Sponge.jar
    - name: Upload Velocity version
      uses: actions/upload-artifact@v1
      with:
        name: Velocity
        path: velocity/target/eZProtector-Velocity.jar
    - name: Upload Waterfall version
      uses: actions/upload-artifact@v1
      with:
        name: Waterfall
        path: waterfall/target/eZProtector-Waterfall.jar
